import Navbar from "@/components/navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="w-screen h-screen bg-slate-100 p-5 flex flex-col gap-5 overflow-y-auto">
          <Navbar />
          <section>{children}</section>
        </main>
      </body>
    </html>
  );
}
